-- Generated by memobase_server/build_init_sql.py on 2024-10-05 00:28:41.514227
CREATE TABLE users (
        id SERIAL NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
        addional_fields JSONB,
        PRIMARY KEY (id)
);
CREATE TABLE general_blobs (
        blob_type CHAR(255) NOT NULL,
        blob_data JSONB NOT NULL,
        user_id INTEGER NOT NULL,
        id SERIAL NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
        addional_fields JSONB,
        PRIMARY KEY (id),
        FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);